base_url = "https://heaptr.me"
title = "heaptr"
description = "personal blog @heaptr"
default_language = "en"
theme = "serene"
output_dir = "public"

compile_sass = true
minify_html = false
build_search_index = false

generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
    { name = "tags" },
    { name = "categories" }
]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
    { theme = "serene-light", filename = "hl-light.css" },
    { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
name = "heaptr"
id = "heaptr"
bio = "re-inventin' the wheel"
avatar = "img/avatar.webp"
links = [
    { name = "GitHub", icon = "github", url = "https://github.com/heaptr" },
    { name = "Email", icon = "email", url = "mailto:null@heaptr.me" },
]

homepage_layout = "about"
force_theme = false

recent_max = 10
recent_more = true
recent_more_text = "more »"

sections = [
    { name = "blog", path = "/blog", is_external = false },
    { name = "projects", path = "/projects", is_external = false },
    { name = "about", path = "/about", is_external = false },
    # { name = "github", path = "https://github.com/heaptr", is_external = true },
]
blog_section_path = "/blog"

nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

display_id = false
blog_categorized = false
blur_effect = true
back_to_top = true

toc = true
copy = true
comment = false
display_tags = true
truncate_summary = false

outdate_alert = false
outdate_alert_days = 120
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = ""
footer_credits = false

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"
