[[project]]
name = "byte"
desc = "A fantasy console running on the 6502 microprocessor with an emulator, assembler, debugging tools, and a code editor for programming."
tags = []
links = [
    {name = "heaptr/byte", url = "https://github.com/heaptr/byte"},
]

[[project]]
name = "pox"
desc = "A complete rewrite of the lox programming language interpreter in Python, featuring extensions to the original language."
tags = []
links = [
    {name = "heaptr/pox", url = "https://github.com/heaptr/pox"},
]

# [[project]]
# name = "mmproxy-rs"
# desc = "A Rust port of the mmproxy project, providing a robust TCP/UDP proxy that preserves client IPs behind load balancers."
# tags = []
# links = [
#     {name = "saiko-tech/mmproxy-rs", url = "https://github.com/saiko-tech/mmproxy-rs"},
# ]

[[project]]
name = "SLMP"
desc = "A client library implementing a subset of the SLMP protocol for interacting with Mitsubishi PLCs."
tags = []
links = [
    {name = "heaptr/SLMP", url = "https://github.com/heaptr/SLMP"},
]

[[project]]
name = "raytracer"
desc = "A raytracer implementation featuring a BMP encoder and a simple linear algebra library for vector math."
tags = []
links = [
    {name = "heaptr/raytracer", url = "https://github.com/heaptr/raytracer"},
]

[[project]]
name = "arche"
desc = "State management for Pygame."
tags = []
links = [
    {name = "heaptr/arche", url = "https://github.com/heaptr/arche"},
]

[[project]]
name = "brainfuck"
desc = "An optimizing brainfuck interpreter and REPL."
tags = []
links = [
    {name = "heaptr/brainfuck", url = "https://github.com/heaptr/brainfuck"},
]

# [[project]]
# name = "memory-rs"
# desc = "Cross platform memory manipulation crate."
# tags = []
# links = [
#     {name = "heaptr/memory-rs", url = "https://github.com/heaptr/memory-rs"},
# ]

# [[project]]
# name = "async-fred-session"
# desc = "Redis backed session store for async-session using fred.rs."
# tags = []
# links = [
#     {name = "heaptr/async-fred-session", url = "https://github.com/heaptr/async-fred-session"},
# ]
